# Generated by Django 3.2.3 on 2021-07-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='profile/picture1.jpg', upload_to='profile/'),
        ),
    ]
