# Generated by Django 3.2.3 on 2021-07-04 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='sentence',
            field=models.CharField(max_length=200),
        ),
    ]
