# Generated by Django 3.2.3 on 2021-07-06 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_review_sentence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booklist',
            options={'permissions': [('special_status', 'Can see the detail of all books')]},
        ),
    ]
