# Generated by Django 3.2.3 on 2021-07-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_booklist_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booklist',
            options={'ordering': ['-date'], 'permissions': [('special_status', 'Can see the detail of all books')]},
        ),
        migrations.AddField(
            model_name='booklist',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
