# Generated by Django 3.2.3 on 2021-09-09 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20210708_1621'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booklist',
            options={'ordering': ['-date']},
        ),
    ]
