# Generated by Django 3.2.3 on 2021-07-09 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_of_delivery',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='date_of_order',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
