# Generated by Django 3.2.3 on 2021-07-09 04:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210709_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_of_delivery',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 14, 9, 46, 6, 187010)),
        ),
    ]
