# Generated by Django 3.2.3 on 2021-07-09 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_date_of_delivery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date_of_order']},
        ),
        migrations.AlterField(
            model_name='order',
            name='date_of_delivery',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_of_order',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
