# Generated by Django 3.2.3 on 2021-07-09 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20210709_1021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['date_of_order']},
        ),
    ]
